Template updated and system time updated
UPHRH-platform/Grievance pull request #30
Opened 2023-11-22 12:15 UTC by Radheshhathwar

2023-11-22 12:24 UTC, shishirsuman092 requested changes

2023-11-22 12:24 UTC, shishirsuman092 commented on src/main/java/org/upsmf/grievance/service/impl/TicketServiceImpl.java
> +        System.out.println(psqlTicket);
remove

2023-11-22 12:24 UTC, shishirsuman092 commented on src/main/java/org/upsmf/grievance/service/impl/TicketServiceImpl.java
> +        System.out.println(ticket);
why is this commented

2023-11-22 12:24 UTC, shishirsuman092 commented on src/main/java/org/upsmf/grievance/controller/TicketController.java
> +    public ResponseEntity<Ticket> save(@RequestBody TicketRequest ticketRequest) {
remove

2023-11-22 12:24 UTC, shishirsuman092 commented on src/main/java/org/upsmf/grievance/controller/TicketController.java
> +        return new ResponseEntity<>(responseTicket, HttpStatus.OK);
remove

2023-11-23 04:53 UTC, Radheshhathwar commented on src/main/java/org/upsmf/grievance/controller/TicketController.java
> +    public ResponseEntity<Ticket> save(@RequestBody TicketRequest ticketRequest) {
Changed

2023-11-23 12:19 UTC, shishirsuman092 requested changes

2023-11-23 12:19 UTC, shishirsuman092 commented on src/main/java/org/upsmf/grievance/service/impl/TicketServiceImpl.java
> +        System.out.println(ticket);
remove

2023-11-23 12:25 UTC, merged